
- name: Add Elasticsearch GPG key.
  rpm_key:
    key: http://packages.elasticsearch.org/GPG-KEY-elasticsearch
    state: present
  become: yes

- name: create elasticsearch repo
  template: src=elasticsearch_repo.j2 dest=/etc/yum.repos.d/elasticsearch.repo
            owner=root group=root mode=0644
  become: yes

- name: Install elasticsearch
  yum: pkg=elasticsearch state=installed
  become: yes