
- include: "Install_{{ elasticsearch_install_method | lower }}_{{ansible_os_family}}.yml"

- name: Config ElasticSearch service 
  service:
    name: elasticsearch
    enabled: yes
    state: started
  become: yes